# {{- if not (.Values.nats.advertise) }}
  apiVersion: v1
  kind: Service
  metadata:
    name: nats-alt-lb
  spec:
    type: LoadBalancer
    selector:
      app: nats-box
    ports:
      - protocol: TCP
        port: 4222
        targetPort: 4222
        nodePort: 30001
        name: nats
      - protocol: TCP
        port: 7422
        targetPort: 7422
        name: leafnodes
      - protocol: TCP
        port: 7522
        targetPort: 7522
        name: gateways
# {{- end }}
